### ISSUE TITLE
Error Loading Layout

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-dashboard#50]
@spestana reported the following error on the webpage:

"Just now I was refreshing the dashboard page (I had to re-route some power cords outside so was waiting to see if my frog was reconnected yet), and encountered an "Error loading layout" message on the dashboard site. A couple of page refreshes and it goes away. But then it comes back again sometimes?"

![image](https://user-images.githubusercontent.com/2559382/136113115-63bd5477-9969-4f2c-aacb-1cbe7693c0f4.png)

He noticed that his console showed the following local log:

![image](https://user-images.githubusercontent.com/2559382/136113172-4ff2df78-04b7-4c69-95bd-f09d9026ddb2.png)

I looked at the Heroku console and saw the following:

```
2021-10-05T22:44:55.823116+00:00 heroku[router]: at=info method=POST path="/_dash-update-component" host=ribbit-network.herokuapp.com request_id=201028a8-8ad1-40a1-ac1d-0b48142720d7 fwd="70.122.146.96" dyno=web.1 connect=0ms service=111ms status=500 bytes=463 protocol=https
2021-10-05T22:44:56.002517+00:00 heroku[router]: at=info method=POST path="/_dash-update-component" host=ribbit-network.herokuapp.com request_id=034d20dc-30ea-4947-84f2-82092fa9e465 fwd="70.122.146.96" dyno=web.1 connect=0ms service=446ms status=200 bytes=75648 protocol=https
2021-10-05T22:44:55.821473+00:00 app[web.1]: Exception on /_dash-update-component [POST]
2021-10-05T22:44:55.821478+00:00 app[web.1]: Traceback (most recent call last):
2021-10-05T22:44:55.821479+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
2021-10-05T22:44:55.821479+00:00 app[web.1]:     response = self.full_dispatch_request()
2021-10-05T22:44:55.821480+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
2021-10-05T22:44:55.821480+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2021-10-05T22:44:55.821481+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
2021-10-05T22:44:55.821481+00:00 app[web.1]:     rv = self.dispatch_request()
2021-10-05T22:44:55.821481+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
2021-10-05T22:44:55.821482+00:00 app[web.1]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-10-05T22:44:55.821482+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/dash/dash.py", line 1079, in dispatch
2021-10-05T22:44:55.821483+00:00 app[web.1]:     response.set_data(func(*args, outputs_list=outputs_list))
2021-10-05T22:44:55.821483+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/dash/dash.py", line 1010, in add_context
2021-10-05T22:44:55.821484+00:00 app[web.1]:     output_value = func(*args, **kwargs)  # %% callback invoked %%
2021-10-05T22:44:55.821484+00:00 app[web.1]:   File "/app/app.py", line 188, in update_map
2021-10-05T22:44:55.821485+00:00 app[web.1]:     df = db.get_map_data()
2021-10-05T22:44:55.821485+00:00 app[web.1]:   File "/app/db.py", line 15, in get_map_data
2021-10-05T22:44:55.821485+00:00 app[web.1]:     return pd.concat(df)
2021-10-05T22:44:55.821485+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 285, in concat
2021-10-05T22:44:55.821486+00:00 app[web.1]:     op = _Concatenator(
2021-10-05T22:44:55.821486+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 320, in __init__
2021-10-05T22:44:55.821486+00:00 app[web.1]:     raise TypeError(
2021-10-05T22:44:55.821486+00:00 app[web.1]: TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"
```

**Comment by keenanjohnson** [comment]
Here's the full error trace file for reference:
[ribbit-network-logs-1633473915601.txt](https://github.com/Ribbit-Network/ribbit-network-dashboard/files/7289695/ribbit-network-logs-1633473915601.txt)

**Comment by spestana** [comment]
A fix could be as simple as changing `pd.concat(df)` to `pd.concat([df])`, but why does the function query_api.query_data_frame() return a dataframe sometimes, and a list of dataframes other times?

**Comment by keenanjohnson** [comment]
Yeah that is weird. Seems like a poor way to design an API on the InfluxDB side IMO haha.
